line_width: 120
dangle_parens: true
additional_commands:
  catkin_package:
    kwargs:
      INCLUDE_DIRS: '*'
      LIBRARIES: '*'
      CATKIN_DEPENDS: '*'
      DEPENDS: '*'
  add_message_files:
    kwargs:
      DIRECTORY: '*'
      FILES: '*'
